Repository UMC-WEGO/WEGO_BE, pull requests merged in 2025-02, with the labels that each got.

#49 [ REFACTOR ] 게시글, 댓글 테이블명 수정
  src/user/user.repository.js
Labels: 🛠️Refactor

#51 [ FEATURE ] 여행 일정 관련 API 추가 개발
  src/home/home.controller.js
  src/home/home.repository.js
  src/home/home.service.js
  src/index.js
  src/user/user.controller.js
  src/user/user.repository.js
  src/user/user.route.js
  src/user/user.service.js
  swagger/home.swagger.yaml
  swagger/user.swagger.yaml
Labels: ✨Feature

#53 [ FIX ] 인기 미션 저장 API 라우터 추가
  src/index.js
Labels: 🐞BugFix

#55 [ FIX ] 사용자 프로필 조회 시 point 응답값 수정
  src/user/user.repository.js
Labels: 🛠️Refactor

#57 Feat: API 수정 및 Swagger 업데이트 (COMMUNITY)
  src/community/community.controller.js
  src/community/community.repository.js
  src/community/community.service.js
  swagger/community.swagger.yaml
Labels: 🛠️Refactor

#59 Fix: 특정 게시물 조회API 수정 (COMMUNITY)
  src/community/community.service.js
  swagger/community.swagger.yaml
Labels: 🐞BugFix

#63 [ FEATURE ] 사용자 프로필 수정 API
  config/s3.js
  package-lock.json
  package.json
  src/home/home.route.js
  src/index.js
  src/user/user.controller.js
  src/user/user.dto.js
  src/user/user.repository.js
  src/user/user.route.js
  src/user/user.service.js
  swagger/user.swagger.yaml
Labels: ✨Feature

#65 Feat: CICD에 S3 관련 변수 추가
  .github/workflows/deploy-main.yml
Labels: ✨Feature

#67 [ FIX ] HOME API 라우터 수정
  src/home/home.route.js
Labels: 🛠️Refactor

#68 [ REFACTOR ] user_id를 토큰으로 변경
  src/community/community.controller.js
  src/community/community.dto.js
  src/community/community.repository.js
  src/community/community.route.js
  src/community/community.service.js
  swagger/community.swagger.yaml
Labels: 🛠️Refactor

#71 [ REFACTOR ] 내가 쓴 글 조회 API 응답값 수정
  src/user/user.dto.js
  src/user/user.repository.js
  swagger/user.swagger.yaml
Labels: 🛠️Refactor

#73 fix: COMMUNITY 관련 API response 수정
  src/community/community.controller.js
  src/community/community.repository.js
  src/community/community.route.js
  swagger/community.swagger.yaml
Labels: 🛠️Refactor

#77 [ FIX ] 프로필 수정 시 nickname, email NULL 오류 수정
  src/user/user.repository.js
Labels: 🐞BugFix

#81 refactor: 게시글 작성자 프로필 조회 API 수정
  src/community/community.repository.js
  swagger/community.swagger.yaml
Labels: 🛠️Refactor

#83 [ REFACTOR ] 랜덤 여행지 추천 API 응답값 리팩토링
  src/home/home.controller.js
  src/home/home.repository.js
  swagger/home.swagger.yaml
Labels: 🛠️Refactor

#85 refactor: 특정 게시물 조회 API 응답 추가
  src/community/community.repository.js
  swagger/community.swagger.yaml
Labels: 🛠️Refactor

#87 Feat: 게시판 S3 적용 (COMMUNITY)
  config/s3.js
  src/community/community.controller.js
  src/community/community.dto.js
  src/community/community.repository.js
  src/community/community.route.js
  src/community/community.service.js
  swagger/community.swagger.yaml
Labels: ✨Feature

#89 refactor: 댓글 삭제 API 수정
  src/community/community.controller.js
  src/community/community.repository.js
  src/community/community.service.js
  swagger/community.swagger.yaml
Labels: 🛠️Refactor

#91 refactor: s3관련 API 응답 수정
  config/s3.js
  src/community/community.controller.js
  swagger/community.swagger.yaml
Labels: 🛠️Refactor

#94 refactor: 댓글 삭제 API 에러 핸들러 수정
  src/community/community.controller.js
  swagger/community.swagger.yaml
Labels: 🛠️Refactor

#96 refactor: S3 사진 업로드 API 에러 핸들러 수정
  config/s3.js
  src/community/community.controller.js
Labels: 🛠️Refactor

#97 Feat: 게시글 작성 API 미션 추가
  src/community/community.repository.js
  src/community/community.service.js
  swagger/community.swagger.yaml
Labels: ✨Feature

#100 refactor: 게시글 작성 API 수정
  src/community/community.controller.js
  swagger/community.swagger.yaml
Labels: 🛠️Refactor

#103 refactor: 전체 게시글 조회 API 응답 수정
  src/community/community.controller.js
  src/community/community.route.js
  swagger/community.swagger.yaml
Labels: 🛠️Refactor

#109 refactor: 인기 게시판 조회 API 응답 수정
  src/community/community.controller.js
  src/community/community.route.js
  swagger/community.swagger.yaml
Labels: 🛠️Refactor

#111 refactor: 인기미션 조회 API 응답 수정
  src/home/home.controller.js
  src/home/home.dto.js
  src/home/home.repository.js
  src/home/home.service.js
  swagger/home.swagger.yaml
Labels: 🛠️Refactor

#113 refactor: 인기 미션 조회 API 수정
  src/home/home.repository.js
Labels: 🛠️Refactor
