Repository UMC-WEGO/WEGO_BE, pull requests merged in 2025-01, with the labels that each got.

#21 [ FEATURE ] HOME 화면 관련 API
  src/home/home.controller.js
  src/home/home.dto.js
  src/home/home.repository.js
  src/home/home.service.js
  src/index.js
  swagger/home.swagger.yaml
Labels: ✨Feature

#26 feat: GitHub Actions에 DB 관련 변수 추가
  .github/workflows/deploy-main.yml
Labels: 🛠️Refactor, 🌏Deploy

#28 [ REFACTOR ] Home 관련 API jwt 인증 반영
  package-lock.json
  src/home/home.controller.js
  src/home/home.service.js
  src/index.js
Labels: 🛠️Refactor

#31 [ FEATURE ] USER 관련 API
  package-lock.json
  package.json
  src/index.js
  src/user/user.controller.js
  src/user/user.dto.js
  src/user/user.repository.js
  src/user/user.route.js
  src/user/user.service.js
  swagger/home.swagger.yaml
  swagger/user.swagger.yaml
Labels: ✨Feature

#33 [ FEATURE ] 랜덤 여행지 추출 방문 증감률 응답값 추가
  src/home/home.dto.js
  src/home/home.repository.js
  swagger/home.swagger.yaml
Labels: ✨Feature

#35 [ REFACTOR ] HOME, USER 관련 API 요청값 수정
  src/home/home.controller.js
  src/home/home.dto.js
  src/home/home.service.js
  src/user/user.controller.js
  swagger/home.swagger.yaml
  swagger/user.swagger.yaml
Labels: 🛠️Refactor

#37 [ REFACTOR ] 여행 날짜 응답값 형식 수정
  src/home/home.controller.js
  src/home/home.dto.js
  src/home/home.repository.js
  swagger/home.swagger.yaml
Labels: 🛠️Refactor

#41 [ FEATURE ] USER 화면 관련 API 추가 개발
  src/user/user.controller.js
  src/user/user.dto.js
  src/user/user.repository.js
  src/user/user.route.js
  src/user/user.service.js
  swagger/home.swagger.yaml
  swagger/user.swagger.yaml
Labels: ✨Feature

#43 [ FEATURE ] HOME 화면 인기 미션 조회 API
  src/home/home.controller.js
  src/home/home.dto.js
  src/home/home.repository.js
  src/home/home.service.js
  src/index.js
  swagger/home.swagger.yaml
  swagger/user.swagger.yaml
Labels: ✨Feature

#45 [ FEATURE ] 미션 인증 사진 응답값 추가
  src/user/user.dto.js
  src/user/user.repository.js
  swagger/user.swagger.yaml
Labels: ✨Feature
